/*
 * Crypto-JS v2.5.2
 * http://code.google.com/p/crypto-js/
 * (c) 2009-2011 by Jeff Mott. All rights reserved.
 * http://code.google.com/p/crypto-js/wiki/License
 */
(function(g){function k(c,a){var b=c._blocksize*4;return b-a.length%b}var j=g.pad={},f=function(c){for(var a=c.pop(),b=1;b<a;b++)c.pop()};j.NoPadding={pad:function(){},unpad:function(){}};j.ZeroPadding={pad:function(c,a){var b=c._blocksize*4,d=a.length%b;if(d!=0)for(d=b-d;d>0;d--)a.push(0)},unpad:function(){}};j.iso7816={pad:function(c,a){var b=k(c,a);for(a.push(128);b>1;b--)a.push(0)},unpad:function(c){for(;c.pop()!=128;);}};j.ansix923={pad:function(c,a){for(var b=k(c,a),d=1;d<b;d++)a.push(0);a.push(b)},
unpad:f};j.iso10126={pad:function(c,a){for(var b=k(c,a),d=1;d<b;d++)a.push(Math.floor(Math.random()*256));a.push(b)},unpad:f};j.pkcs7={pad:function(c,a){for(var b=k(c,a),d=0;d<b;d++)a.push(b)},unpad:f};var g=g.mode={},h=g.Mode=function(c){if(c)this._padding=c};h.prototype={encrypt:function(c,a,b){this._padding.pad(c,a);this._doEncrypt(c,a,b)},decrypt:function(c,a,b){this._doDecrypt(c,a,b);this._padding.unpad(a)},_padding:j.iso7816};f=(g.ECB=function(){h.apply(this,arguments)}).prototype=new h;f._doEncrypt=
function(c,a){for(var b=c._blocksize*4,d=0;d<a.length;d+=b)c._encryptblock(a,d)};f._doDecrypt=function(c,a){for(var b=c._blocksize*4,d=0;d<a.length;d+=b)c._decryptblock(a,d)};f.fixOptions=function(c){c.iv=[]};f=(g.CBC=function(){h.apply(this,arguments)}).prototype=new h;f._doEncrypt=function(c,a,b){for(var d=c._blocksize*4,e=0;e<a.length;e+=d){if(e==0)for(var i=0;i<d;i++)a[i]^=b[i];else for(i=0;i<d;i++)a[e+i]^=a[e+i-d];c._encryptblock(a,e)}};f._doDecrypt=function(c,a,b){for(var d=c._blocksize*4,e=
0;e<a.length;e+=d){var i=a.slice(e,e+d);c._decryptblock(a,e);for(var f=0;f<d;f++)a[e+f]^=b[f];b=i}};f=(g.CFB=function(){h.apply(this,arguments)}).prototype=new h;f._padding=j.NoPadding;f._doEncrypt=function(c,a,b){for(var d=c._blocksize*4,b=b.slice(0),e=0;e<a.length;e++){var f=e%d;f==0&&c._encryptblock(b,0);a[e]^=b[f];b[f]=a[e]}};f._doDecrypt=function(c,a,b){for(var d=c._blocksize*4,b=b.slice(0),e=0;e<a.length;e++){var f=e%d;f==0&&c._encryptblock(b,0);var g=a[e];a[e]^=b[f];b[f]=g}};f=(g.OFB=function(){h.apply(this,
arguments)}).prototype=new h;f._padding=j.NoPadding;f._doEncrypt=function(c,a,b){for(var d=c._blocksize*4,b=b.slice(0),e=0;e<a.length;e++)e%d==0&&c._encryptblock(b,0),a[e]^=b[e%d]};f._doDecrypt=f._doEncrypt;g=(g.CTR=function(){h.apply(this,arguments)}).prototype=new h;g._padding=j.NoPadding;g._doEncrypt=function(c,a,b){for(var d=c._blocksize*4,e=0;e<a.length;){var f=b.slice(0);c._encryptblock(f,0);for(var g=0;e<a.length&&g<d;g++,e++)a[e]^=f[g];++b[d-1]==256&&(b[d-1]=0,++b[d-2]==256&&(b[d-2]=0,++b[d-
3]==256&&(b[d-3]=0,++b[d-4])))}};g._doDecrypt=g._doEncrypt})(Crypto);
